blog/forms/article.py
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField
from flask_wtf import FlaskForm


class CreateArticleForm(FlaskForm):
    title = StringField("Title", [validators.DataRequired()])
    text = TextAreaField("Text",  [validators.DataRequired()])
    tags = SelectMultipleField("Tags", coerce=int)
    submit = SubmitField("Create")

blog/articles/views.py
from http.client import HTTPException
from flask_login import current_user, login_required
import requests
from werkzeug.exceptions import NotFound
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from sqlalchemy.orm import load_only, joinedload
from blog.forms.article import CreateArticleForm

article_app = Blueprint('article_app', __name__,
                        url_prefix='/articles', static_folder='../static')
TITLES = []


@article_app.route('/')
def article_list():
    from blog.models import Article
    articles = Article.query.all()   
    return render_template('articles/list.html', articles=articles)


@article_app.route('/<int:pk>')
def get_article(pk: int):
    from blog.models import Article
    article = Article.query.filter_by(id=pk).options(joinedload(Article.tags)).one_or_none()
    if article is None:
        raise NotFound
    return render_template('articles/detail.html', article=article)


@article_app.route('/create/', methods=['GET', 'POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    from blog.models import Article, Author, Tag
    from blog.app import db
    form.tags.choices = [(tag.id, tag.name)for tag in Tag.query.order_by("name")]

    if request.method == 'POST' and form.validate_on_submit():
        article = Article(title=form.title.data, text=form.text.data)
        db.session.add(article)             
        if current_user.author:
            article.author = current_user.author
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            article.author = current_user.author
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)    

        db.session.commit()
        return redirect(url_for('article_app.get_article', pk=article.id))
    return render_template('articles/create.html', form=form)


@article_app.route('tag/<int:pk>')
def get_article_by_tag(pk: int):
    from blog.models import article_tag_associations_table, Article, Tag
    query_article = Article.query.join(article_tag_associations_table).join(Tag).filter((article_tag_associations_table.c.article_id==Article.id)&(article_tag_associations_table.c.tag_id==Tag.id)).filter(article_tag_associations_table.c.tag_id==pk)
    
    if query_article is None:
        raise NotFound
    return render_template('articles/articles_by_tag.html',articles=query_article)


@article_app.route('/<int:id>/edit',  methods=['GET', 'POST'])
@login_required
def update_article(id):
    from blog.models import Article
    from blog.app import db    
    article_to_update = Article.query.filter(Article.id==id).first()
    form = CreateArticleForm(obj=article_to_update )
    if request.method =='POST':
        form = CreateArticleForm(formdata=request.form, obj=article_to_update)
        form.populate_obj(article_to_update)        
        db.session.commit()           
        flash("Успешно изменили статью")
        return redirect(url_for('article_app.get_article', pk=id))
       
           
    form = CreateArticleForm(obj=article_to_update)
    return render_template('articles/update.html', form=form,article_to_update=article_to_update)
   
 

blog/templates/articles/articles_by_tag.html
{% extends 'users/base.html' %} {% block title %} Список статей {% endblock %}
{% block body %}
<div class="vstack gap-2">
  <h5>Статьи</h5>
  {% for article in articles %}
  <div class="p-2">
    <ul>
      <li>{{article.title}}</li>
      <li>
        {{article.author.user.first_name}} {{article.author.user.last_name}}
      </li>
    </ul>
  </div>
  {% endfor %}
</div>

{% endblock body %}

blog/templates/articles/create.html
{% extends 'users/base.html' %} {% from "macro/formhelpers.html" import
render_field %} {% block title %} Создать статью {% endblock %} {% block body %}

<form method="POST">
  {{form.csrf_token()}} {% for field in ['title', 'text', 'tags']%}
  {{render_field(form[field])}} {% endfor %} {{ form.submit(class="btn
  btn-primary")}}
</form>

{% endblock body %}

blog/templates/articles/detail.html
{% extends 'users/base.html' %} {% block title %} Статья полностью {% endblock
title %} {% block body %}
<div class="row">
  <div class="col-md-12">{{article.text}}</div>
</div>
<div class="row">
  <div class="col-6">
    <div>
      <small class="text-muted"
        >Автор статьи: {{article.author.user.email}}</small
      >
    </div>
  </div>
  <div class="col-6">
    {% for tag in article.tags %}
        <a href="{{url_for('article_app.get_article_by_tag', pk=tag.id)}}"> <span class="badge badge-primary">{{tag.name}}</span>
    {% endfor %}
  </div>
</div>

{% endblock body %}

blog/templates/articles/list.html
{% extends 'users/base.html' %}
{% block title %}
   Список статей
{% endblock  %}
{% block body %}
<div class="vstack gap-2">
    <h5>Статьи</h5>
    {{count_articles}}
    {% for article in articles  %}
        <div class="p-2">
       
         <ul>
            <li><a href="{{url_for('article_app.get_article', pk=article.id)}}">{{article.title}}</li>
        </ul>
        <div>
            <a href="{{url_for('article_app.update_article', id=article.id)}}" class="btn btn-outline-secondary">Изменить статью</a>
            </div>
    </div>
    {% endfor %}
    
</div>

{% endblock body %}

blog/templates/articles/update.html
{% extends 'users/base.html' %} {% from "macro/formhelpers.html" import
render_field %} {% block title %} Создать статью {% endblock %} {% block body %}

<form  method="POST" >
    {% for field in form %}
    <div class="form-group">
      {{field.label()}}
    {{field(class="form-control")}}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Sibmit</button>
</form>


{% endblock body %}