blog/forms/user.py
from wtforms import StringField, validators, PasswordField, SubmitField
from flask_wtf import FlaskForm


class UserRegisterForm(FlaskForm):
    first_name = StringField("First name")
    last_name = StringField("Last name")
    email = StringField(
        "E-mail", [validators.DataRequired(), validators.Email()])
    password = PasswordField("Password", [validators.DataRequired(), validators.EqualTo(
        'confirm_password', message="Пароль не совпадает")])
    confirm_password = PasswordField(
        "Confirm password", [validators.DataRequired()])
    submit = SubmitField("Register")

blog/articles/views.py
from http.client import HTTPException
from flask_login import current_user, login_required
import requests
from werkzeug.exceptions import NotFound
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from sqlalchemy.orm import load_only, joinedload
from blog.forms.article import CreateArticleForm

article_app = Blueprint('article_app', __name__,
                        url_prefix='/articles', static_folder='../static')
TITLES = []


@article_app.route('/')
def article_list():
    from blog.models import Article
    articles = Article.query.all()   
    return render_template('articles/list.html', articles=articles)


@article_app.route('/<int:pk>')
def get_article(pk: int):
    from blog.models import Article
    article = Article.query.filter_by(id=pk).options(joinedload(Article.tags)).one_or_none()
    if article is None:
        raise NotFound
    return render_template('articles/detail.html', article=article)


@article_app.route('/create/', methods=['GET', 'POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    from blog.models import Article, Author, Tag
    from blog.app import db
    form.tags.choices = [(tag.id, tag.name)for tag in Tag.query.order_by("name")]

    if request.method == 'POST' and form.validate_on_submit():
        article = Article(title=form.title.data, text=form.text.data)
        db.session.add(article)             
        if current_user.author:
            article.author = current_user.author
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            article.author = current_user.author
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)    

        db.session.commit()
        return redirect(url_for('article_app.get_article', pk=article.id))
    return render_template('articles/create.html', form=form)


@article_app.route('tag/<int:pk>')
def get_article_by_tag(pk: int):
    from blog.models import article_tag_associations_table, Article, Tag
    query_article = Article.query.join(article_tag_associations_table).join(Tag).filter((article_tag_associations_table.c.article_id==Article.id)&(article_tag_associations_table.c.tag_id==Tag.id)).filter(article_tag_associations_table.c.tag_id==pk)
    
    if query_article is None:
        raise NotFound
    return render_template('articles/articles_by_tag.html',articles=query_article)


@article_app.route('/<int:id>/edit',  methods=['GET', 'POST'])
@login_required
def update_article(id):
    from blog.models import Article
    from blog.app import db    
    article_to_update = Article.query.filter(Article.id==id).first()
    form = CreateArticleForm(obj=article_to_update )
    if request.method =='POST':
        form = CreateArticleForm(formdata=request.form, obj=article_to_update)
        form.populate_obj(article_to_update)        
        db.session.commit()           
        flash("Успешно изменили статью")
        return redirect(url_for('article_app.get_article', pk=id))
       
           
    form = CreateArticleForm(obj=article_to_update)
    return render_template('articles/update.html', form=form,article_to_update=article_to_update)
   
 

blog/authors/views.py
from flask import Blueprint, redirect, render_template, request, url_for


authors = Blueprint('authors', __name__,
                     url_prefix='/authors', static_folder='../static')

@authors.route('/')
def authors_list():
    from blog.models import Author
    authors = Author.query.all()
    return render_template('authors/list.html', authors=authors)

blog/user/views.py
from sqlite3 import IntegrityError
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound
from flask import Blueprint, redirect, render_template, request, url_for
from blog.forms.user import UserRegisterForm
from werkzeug.security import generate_password_hash


user_app = Blueprint('user_app', __name__,
                     url_prefix='/users', static_folder='../static')


@user_app.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user_app.get_user', pk=current_user.id))
    form = UserRegisterForm(request.form)
    errors = []
    from blog.models import User
    from blog.app import db
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('email not unique')
            return render_template('users/register.html', form=form)
        user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,

        )
        user.password = generate_password_hash(form.password.data)
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            errors = 'Some error'
        else:
            db.session.commit()
            login_user(user)

    return render_template('users/register.html', form=form, errors=errors)


@user_app.route('/')
def user_list():
    from blog.models import User
    users = User.query.all()
    return render_template('users/list.html', users=users)


@user_app.route('/<int:pk>')
@login_required
def get_user(pk: int):
    from blog.models import User
    user = User.query.filter_by(id=pk).one_or_none()
    return render_template('users/detail.html', user=user)

blog/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />
    <!-- Bootstrap CSS -->
    {% block css %}
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    />
    {% endblock %}
    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    {% include 'users/navbar.html' %}

    <div class="container">{% block body %} {% endblock %}</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% block js %}

    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    {% include 'users/footer.html' %} {% endblock %}
  </body>
</html>

blog/templates/users/detail.html
{% extends 'users/base.html' %} {% block title %} User detail {% endblock title
%} {% block body %}
<h3>{{user.email}} {{user.id}}</h3>
{% endblock body %}

blog/templates/users/footer.html
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #55acee"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #333333"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2023 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

blog/templates/users/list.html
{% extends 'users/base.html' %}
{% block title %}
    Список пользователей
{% endblock  %}
{% block body %}
<div class="vstack gap-2">
    <h5>Пользователи</h5>
    {% for user in users  %}
    <div class="p-2">
      
         <ul>
            <li><a href="{{url_for('user_app.get_user', pk=user.id)}}">{{user.email}}</li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endblock body %}

blog/templates/users/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Меню</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('user_app.user_list')}}"
          >Пользователи <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('article_app.article_list')}}"
          >Статьи</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('authors.authors_list')}}"
          >Авторы</a
        >
      </li>
      {% if current_user.is_authenticated%}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('article_app.create_article')}}"
          >Создать статью</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

blog/templates/users/register.html
{% extends 'users/base.html' %} {% from "macro/formhelpers.html" import
render_field %} {% block title %} User register {% endblock %} {% block body %}
{% if errors%} {% for error in errors %}
<div class="alert alert-danger" role="alert">{{error}}</div>
{% endfor %} {% endif %}
<form method="POST">
  {{form.csrf_token()}} {% for field in ['first_name', 'last_name', 'email',
  'password', 'confirm_password']%} {{render_field(form[field])}} {% endfor %}
  {{ form.submit(class="btn btn-primary")}}
</form>

{% endblock body %}